Dataset:
  dataset_name: cardiac
  use_data_aug: False
  subfolder: WeaklyAnnotations
  metainfoGenerator_dict:
    name: IndividualBoundGenerator
    eps: 0.1

Dataloader:
  num_workers: 1
  batch_size: 1
  shuffle: True
  group_train: True

Arch:
  name: enet
  num_classes: 2
Optim:
  name: Adam
  lr: 0.005
  weight_decay: 0.00001
Scheduler:
  name: StepLR
  step_size: 100
  gamma: 0.5

ADMM_Method:
  name: gc_size_3d
  OptimInnerLoopNum: 1
  ADMMLoopNum: 100
  device: cuda
  visualization: True
  gc_method: gt_oracle
  p_u: 10.0
  p_v: 10.0

# add the following parameters in argparser
#  lamda: 0.5
#  sigma: 0.005
#  kernel_size: 5

Trainer:
  save_dir: runs/prostate
  max_epoch: 500
  use_tqdm: True
#  checkpoint: archives/PROSTATE_gt_oracle/gc_size

Loss:
  name: partial_ce

