Dataset:
  dataset_name: prostate
  use_data_aug: False
  metainfoGenerator_dict:
    name: IndividualBoundGenerator
    eps: 0.05

Dataloader:
  num_workers: 8
  batch_size: 8
  shuffle: True

Arch:
  name: enet
  num_classes: 2
Optim:
  name: Adam
  lr: 0.005
  weight_decay: 0.00001
Scheduler:
  name: StepLR
  step_size: 100
  gamma: 0.1


ADMM_Method:
  name: size
  OptimInnerLoopNum: 1
  ADMMLoopNum: 1
  device: cuda
Trainer:
  save_dir: runs/first_try
  max_epoch: 300

Loss:
  name: partial_ce
