Dataset:
  dataset_name: cardiac
  use_data_aug: False
  subfolder: WeaklyAnnotations
  metainfoGenerator_dict:
    name: IndividualBoundGenerator
    eps: 0.1

Dataloader:
  num_workers: 4
  batch_size: 4
  shuffle: True

Arch:
  name: enet
  num_classes: 2
Optim:
  name: Adam
  lr: 0.0005
  weight_decay: 0.00001
Scheduler:
  name: StepLR
  step_size: 150
  gamma: 0.1

ADMM_Method:
  name: gc_size
  OptimInnerLoopNum: 5
  ADMMLoopNum: 2
  device: cuda
  visualization: False

# add the following parameters in argparser
#  lamda: 0.5
#  sigma: 0.005
#  kernel_size: 5

Trainer:
  save_dir: runs/prostate
  max_epoch: 500
  use_tqdm: True
#  checkpoint: archives/PROSTATE/gc_size

Loss:
  name: partial_ce

